# Generated by Django 4.2.5 on 2023-09-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zipcode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("zipcode", models.CharField(max_length=200)),
                ("settlement", models.CharField(max_length=500)),
                ("settlement_type", models.CharField(max_length=200)),
                ("municipality", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("settlement_zipcode", models.CharField(max_length=200)),
                ("state_code", models.IntegerField()),
                ("office_zipcode", models.CharField(max_length=200)),
                ("settlement_type_code", models.CharField(max_length=50)),
                ("settlement_id", models.IntegerField(unique=True)),
                ("zone", models.CharField(max_length=200)),
                ("city_code", models.CharField(blank=True, max_length=50, null=True)),
                ("municipality_code", models.IntegerField()),
            ],
            options={
                "db_table": "Zipcode",
            },
        ),
    ]
