# Generated by Django 4.2.5 on 2023-09-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zipcode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcode",
            name="settlement_id",
            field=models.IntegerField(),
        ),
    ]
